### PR TITLE
[#4908] Python 2.7.15 update.

### PR DESCRIPTION
**Pull request by dumol**
#Scope
=====

Python 2.7.15 was released a few days ago and there are some security fixes in there (including an updated copy of `expat`), according to ​https://github.com/python/cpython/blob/2.7/Misc/NEWS.d/2.7.15rc1.rst, so I'm treating this as a security issue.

Changes
=======

Updated Python sources and Windows installer to 2.7.15 from upstream.

Updated our patches accordingly.

**Drive-by changes**:

 * `nis` modules is disabled, as we don't use it and it links to lots of libs (GSS-API, Kerberos etc.)
 * a second AIX-specific hack for `ld_so_aix` woes, as upstream fixes from Python's bug tracker do not cover all scenarios
 * cherry-picked Ubuntu 18.04 updates from #103
 * reverted `chevah-keycert` tests
 * excepted unsupported platforms such as `solaris11-sparc` and `freebsd11` from running `compat` tests.
 * minor tweaks for Solaris 10.

How to try and test the changes
===============================

reviewers: @adiroiban 

Review changes to master in `chevah_build`, `functions.sh` and `src/python/*.patch`.
Think of a better solution for AIX's `ld_so_aix` woes?
Run the automated tests.

### CODE REVIEW

**Comment by dumol** [comment]
**needs-review**

**Comment by dumol** [comment]
Solaris 10 builds were broken with the installation of OpenSSL 1.0.2 patches.

**needs-changes**

**Comment by dumol** [comment]
I've tried (mostly in my spare time) to fix Solaris 10 builds against OpenSSL 0.9.7 in `/usr/sfw` when there is an OpenSSL 1.0.2 in `/usr`, made some progress, but there are strong assumptions in Python's `setup.py` in favour of `/usr` headers and libs, I wouldn't overturn them for such a corner case.

I think we can conclude that's it's not worthy to support such a setup. Solaris 10 builds were fine with rev 
b2a170d  in https://chevah.com/buildbot/builders/python-package-gk-review/builds/22, before installing OpenSSL 1.0.2 patches from Oracle. And the changes since then are not at all relevant to Solaris.

Building against OpenSSL 1.0.2 in Solaris 10 will be worked upon in #103.

**needs-review**

**Comment by adiroiban** [comment]
I have updated chevah-keycert https://github.com/chevah/chevah-keycert/pull/35.
I hope it will now work on AIX .

But if tests are still failing, feel free to remove the chevah-keycert test.

Thanks!

**Comment by dumol** [comment]
Thanks, let's see… It wasn't that bad, and for some OS'es the fixes seemed straightforward from what I've seen yesterday when taking a quick look.

**Comment by dumol** [comment]
Actually, it's worse, nothing passes, it seems `./brink.sh test` fails for `chevah-keycert` for all slaves: https://chevah.com/buildbot/builders/python-package-gk-review/builds/28

Previous revision had some passes: https://chevah.com/buildbot/builders/python-package-gk-review/builds/27

**Comment by adiroiban** [comment]
you can remove the keycert tests

**Comment by dumol** [comment]
Was thinking of a different solution, enabling `compat` and `chevah-keycert` tests only for some platforms. 

I don't like that `python-package` builds fail for some unsupported platforms such as `fbsd-11` and `solaris-11-sparc` just because the compat tests fail and compat failures on those platforms will not be fixed. Maybe `compat` tests should only be enabled for supported platforms?

In the same vein we can enable `chevah-keycert` only for some platforms, given that tests pass now. In time we should aim for parity with `compat`, but this should be better than nothing.

But for that `chevah-keycert` shouldn't fail on every platform, like it does now… :-]

**Comment by dumol** [comment]
I've tried a bit of debugging for the `chevah-keycert` test failures…

Interestingly, on Ubuntu 160.4 `./brink.sh test` only fails through buildbot, not when executed on the build slave through a shell. I've tried executing with `bash -x`, but apart from a minor $PATH diff, things look the same until the end.

Output from running through buildbot:
```
  + execute_venv test
  + build/venv/bin/python -c 'from paver.tasks import main; main()' test
  ---> pavement.test
  /srv/buildslave/runtime/build-ubuntu1604-x64/slave/python-package-ubuntu-1604/build/build/chevah-keycert/build/venv/lib/python2.7/site-packages/Crypto/Util/number.py:57: PowmInsecureWarning: Not using mpz_powm_sec.  You should rebuil
    _warn("Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.", PowmInsecureWarning)
  ...............................................................................................................................
  + exit_code=1
```


Output from running in a shell:
```
+ execute_venv test
+ build/venv/bin/python -c 'from paver.tasks import main; main()' test
---> pavement.test
/srv/buildslave/runtime/build-ubuntu1604-x64/slave/python-package-ubuntu-1604/build/build/chevah-keycert/build/venv/lib/python2.7/site-packages/Crypto/Util/number.py:57: PowmInsecureWarning: Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.
  _warn("Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.", PowmInsecureWarning)
...............................................................................................................................
Name                                      Stmts   Miss  Cover
-------------------------------------------------------------
chevah/keycert/__init__.py                    5      0   100%
chevah/keycert/common.py                     77     25    68%
chevah/keycert/exceptions.py                  8      0   100%
chevah/keycert/sexpy.py                      36      1    97%
chevah/keycert/ssh.py                       668     12    98%
chevah/keycert/ssl.py                        97      0   100%
chevah/keycert/tests/__init__.py              6      0   100%
chevah/keycert/tests/helpers.py              33      0   100%
chevah/keycert/tests/keydata.py              25      0   100%
chevah/keycert/tests/test_exceptions.py      12      0   100%
chevah/keycert/tests/test_ssh.py            713      0   100%
chevah/keycert/tests/test_ssl.py            125      0   100%
-------------------------------------------------------------
TOTAL                                      1805     38    98%
----------------------------------------------------------------------
Ran 127 tests in 1.733s

OK
Name                                      Stmts   Miss  Cover
-------------------------------------------------------------
chevah/keycert/tests/__init__.py              6      0   100%
chevah/keycert/tests/helpers.py              33      0   100%
chevah/keycert/tests/keydata.py              25      0   100%
chevah/keycert/tests/test_exceptions.py      12      0   100%
chevah/keycert/tests/test_ssh.py            713      0   100%
chevah/keycert/tests/test_ssl.py            125      0   100%
-------------------------------------------------------------
TOTAL                                       914      0   100%
Tests coverage OK
See HTML coverate in build/cover
+ exit_code=0
```

**Comment by dumol** [comment]
There seems to be a problem with the **error code** from .`/brink test` (obviously). When coverage is not good enough (/me thinks), eg. for https://chevah.com/buildbot/builders/python-package-win-xp-dev/builds/65/steps/test_1/logs/stdio. The error code for this failure was 2 and the build failed, although coverage looks good (again, /me thinks).

I changed `chevah_build` to soft fail for `chevah-keycert` tests for now to move ahead…

**Pull request merged**
