### PR TITLE
[#5250] Added subprocess32 module.

### PR DESCRIPTION
**Pull request by dumol**
Scope
=====

Include `subprocess32` so that we can get some better timeout support, needed to support the future multi-cpu code.

Changes
=======

Added Windows wheel and sources on our PyPI servers.

Included `subprocess32` in PIP_LIBRARIES* for all OS'es.

Fixed minor compilation issue on Solaris.

Added `subprocess32` to the spreadsheet with external deps and known vulnerabilities: https://docs.google.com/spreadsheets/d/12N64qFknk91f0YzEFEZ62jJ8VHfhrX2OT0nNTCn9bvY/

Maybe we should import this as an CSV file in this repo?

**Drive-by fixes**:
  * Slightly improved tests for some modules such as `scandir`, `setproctitle`, etc.
  * Stopped building `psutil` on Solaris 10 and 11.2 as requested below.
  * Removed sources for `Cython` module, not really needed, as it builds just fine through PIP.

How to try and test the changes
===============================

reviewers: @adiroiban 

Please review changes:
```
git diff master chevah_build python-modules/chevah-python-test/
```

Look for anything not green at https://chevah.com/buildbot/waterfall?category=python-package :-]

### CODE REVIEW

**Comment by dumol** [comment]
**needs-review**

**Comment by adiroiban** [comment]
ah... please remove psutil from solaris as it does not work.
no need to spend more time with it... or use the previous verions for solaris.

thanks!

----------

the change in psutils is making some tests in Windows to fail...

I will try to fix them.

But in the future we need to look at creating wheel files for OSX / Linux and Windows and deploy them independent of the whole python-package.

**Comment by adiroiban** [comment]
hm... we need to sync python-package with chevah/server build slaves.

it looks like some platforms are missing, for example
* ubuntu-1404
* debian-8-x64

Thanks!

**Comment by dumol** [comment]
> hm... we need to sync python-package with chevah/server build slaves.

Sorry, what do you mean? Missing testing packages?

On Friday evening I have uploaded production packages for the latest rev in master: `690bed90`. This is the corresponding build: https://chevah.com/buildbot/builders/python-package-group-all/builds/8.

**Comment by adiroiban** [comment]
Thanks. I was working with db5f082f ... will update to 690bed90 thanks!

**Pull request merged**
