### PR TITLE
[#2681] Update paver.sh from brink.

### PR DESCRIPTION
**Pull request by dumol**
Problem?
------------
`paver.sh` in brink got so many improvements over the one in python-package's master that it's hard to review a ticket in which it is updated as a drive-by fix.

Solution?
------------
Update `paver.sh` from brink.

How to test?
------------------
Please review changes.
Run the tests.

reviewer: @adiroiban

### CODE REVIEW

**Comment by dumol** [comment]
**needs-review**

**Comment by adiroiban** [comment]
Looks good... but there are conflicts

approved-at bb8e705

**Comment by dumol** [comment]
What do you mean by _conflicts_? Please explain… Thanks!

**Comment by adiroiban** [comment]
See  githhub details:

We can’t automatically merge this pull request.
Use the command line to resolve conflicts before continuing.

step1
```
git fetch origin
git checkout -b 2681-update-paver-from-brink origin/2681-update-paver-from-brink
git merge master
``

**Comment by dumol** [comment]
There shouldn't be any as far as I know. I have just branched from master and then copied over `paver.sh`. Nothing else has been committed to master in the mean time. Let's see…

**Pull request merged**
