### PR TITLE
[#5298] Generic glibc-based Linux runtime.

### PR DESCRIPTION
**Pull request by dumol**
Scope
=====

Few years back, we had a generic Linux runtime built on Debian's _oldstable_ version. However, since then, OpenSSL's APIs have become more volatile.

So let's have a generic Linux version that includes OpenSSL for everything, as we actually include it for SLES 11 anyway (through the `cryptography` wheel with OpenSSL 1.1.x).

Include everything else that is needed to have it working on any glibc-based Linux distro: libffi, zlib, ~libedit~.

Changes
=======

Build a generic Linux build with **statically-linked OpenSSL libs** on SLES 11 and unsupported glibc-based distro (such as RHEL 6, Arch, non-LTS Ubuntu, older LTS versions with OpenSSL 1.0.1, older Debians with OpenSSL 1.0.1, etc). 

A generic Linux build **must** link only to glibc's libs. This means the generic `python-package` build will:
  * fail on _RHEL 6_ - because `crypt` module links to  `/lib64/libfreebl3.so`, which belongs to the `nss-softokn-freebl` package, which can't be uninstalled.
 * fail on _Arch Linux_ - because various modules link to `/usr/lib/libncursesw.so.6` (`setproctitle`, `psutil`, `bcrypt`, `cython`, `scandir`, `posixsubprocess32`).
 * pass on _Ubuntu 14.04_.

As glibc is backward-compatible, not forward-compatible, to support SLES 11 with the generic linux build, you have to build it on a system where glibc is the same version or older. More on this at https://abi-laboratory.pro/?view=timeline&l=glibc.

Therefore, ALL slaves set for building generic Linux runtime (`rhel-6`, `ubuntu-1404`, `arch`) have been disabled for `python-package` in our Buildbot setup through https://github.com/chevah/salt-master/commit/feec2889a0bdfb5b46ec3c7aea1a577fba4407f4. Except `sles-11`, which has the oldest glibc version:  **`2.11.3`**.

**Drive-by fixes**:
  - [x] Debian builds with `libedit`, as there's no more a need for it to be as compatible as possible.
  - [x] RHEL/SLES detected through `/etc/os-release` too, it is now present on all supported distros.
  - [x] Refactored `detect_os()` in `paver.sh` for improved control flow while at it.
  - [x] All error outputs in `paver.sh` should go to `stderr`, as in `chevah_build`.
  - [x] Shortened some OS names: `win`, `amzn`, `obsd`, `fbsd`, `sol`.
  - [ ] Updated external deps spreadsheets (to be further updated accordingly if PR passes review)

How to try and test the changes
===============================

reviewers: @adiroiban 

Assess above choices.

Please review changes, eg.:
```
git diff master paver.conf paver.sh chevah_build src/openssl/chevahbs python-modules/chevah-python-test/
```

Run the automated tests for `python-package`, eg. https://chevah.com/buildbot/builders/python-package-group-all/builds/19

Run the automated tests for `compat` with generic Linux runtime for `sles-11` / `rhel-6` / `arch`, eg. https://chevah.com/buildbot/builders/compat-group-all/builds/19

### CODE REVIEW

**Comment by dumol** [comment]
More of a FYI for now, before leaving for a week…

Check SLES 11 build for the current progress: https://chevah.com/buildbot/builders/python-package-sles-11/builds/74/

As the Python's `ssl` module still links to the system OpenSSL libs, there's a need to also build them statically as we do with `libffi` and `zlib`. If you have a better idea, do let me know, thanks!

**needs-review**

**Comment by dumol** [comment]
For not linking `ssl` module to system OpenSSL libs.

**needs-changes**

**Comment by dumol** [comment]
**needs-review**

**Comment by dumol** [comment]
Shortened OS names break `compat` tests for Windows. Fixing that requires updating `brink`.

**needs-changes**

**Comment by adiroiban** [comment]
Thanks for working on this. please try brink 0.71.0 :)

Looking forward to the generic linux version :)

**Comment by dumol** [comment]
An epic journey spanning two 1-week vacations for me, but everything¹ should work now.

**needs-review**

  1. Except when it doesn't. :-]

**Comment by dumol** [comment]
Server PR using binaries generated in this branch: https://github.com/chevah/server/pull/1600

**Pull request merged**
