### PR TITLE
[#5247] Stop using Homebrew's OpenSSL libs.

### PR DESCRIPTION
**Pull request by dumol**
Scope
=====

Using OS-provided LibreSSL libs for both Python's `ssl` and `cryptography` modules, if feasible. As discussed in Track ticket #5243.

This would mean supporting only macOS 10.13 and newer. 

Changes
=======

Imported LibreSSL 2.2.7 sources to copy needed headers during the build phase on macOS 10.13.

**Drive-by fixes**:
  * Stop building zlib on macOS, as we should only build on 10.13, where the zlib headers are present
  * Renamed the names for Apple OS'es to `osx` for OS X 10.8 - macOS 10.12, and `macos` for macOS 10.13 and newer
  * Removed special treatment for SLES 11 with SM.
  * Imported  spreadsheet with dependencies and possible vulnerabilities, for now as both CSV and  ODS.

How to try and test the changes
===============================

reviewers: @adiroiban 

Please review changes: `git diff master paver.sh chevah_build python-modules/chevah-python-test/`

Run the automated `python-package` tests on macOS 10.13, eg.:
https://chevah.com/buildbot/builders/python-package-macos-1013/builds/1

Try the testing packages on both macOS 10.13 and macOS 10.14 for compat / server / etc. Eg.: 
https://chevah.com/buildbot/builders/compat-macos-1014/builds/10
https://chevah.com/buildbot/builders/server-macos-1013/builds/4
https://chevah.com/buildbot/builders/server-macos-1014/builds/4

### CODE REVIEW

**Comment by adiroiban** [comment]
thanks for working on this.
I think that removing homebrew dependency can help with PROD deployment

note that LibreSSL will only be used for dev/testing tools using the Python standard library.

For heavy lifting of protecting network connection with TLS we will still use Python cryptography lib which AFAIK only works with OpenSSL

**Comment by dumol** [comment]
LibreSSL will be used for everything, just as in OpenBSD. LibreSSL is a fork of OpenSSL that kept API compatibility, so it was working with `cryptography` (almost) all the time.

Anyway, switching to LibreSSL in macOS 10.13 was quick and easy,  here's a build for you to check: https://chevah.com/buildbot/builders/python-package-macos-1013/builds/0. Excerpts:

```
python 2.7.16 (bd07d0d0, Apr 17 2019, 11:18:32) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
zlib 1.0
stdlib ssl LibreSSL 2.2.7
cryptography 2.6.1 - OpenSSL LibreSSL 2.2.7
pyOpenSSL 19.0.0 - OpenSSL LibreSSL 2.2.7
PyCrypto 2.6.1
PyCryptodome 3.6.6
ctypes 1.1.0
gmpy2 2.0.8 with:
	MP (Multiple-precision library) - GMP 6.1.2
	MPFR (Floating-point library) - None
	MPC (Complex library) - None
Cython 0.29.5
"subprocess32" module is present.
pysqlite2 2.8.3 - sqlite 3.27.1
setproctitle 1.1.10
psutil 5.6.1
"readline" module is present.
```

**Comment by dumol** [comment]
A bit rough around the edges. Asking for feedback…

Would also like to shorten GIT rev from 8 to 7 characters, to match GitHub's short revs. What do you think?

**needs-review**

**Comment by dumol** [comment]
A bit rough around the edges. Asking for feedback for now…

Fine with using the following `OS` names?
  * `macos` for macOS 10.13 and newer (with the OS-included LibreSSL 2.2.7 for both Python's `ssl` and `cryptography`) 
  * `osx` for OS X 10.8 and newer, up to and including macOS 10.12 (with OS-included OpenSSL 0.9.8 for Python's `ssl` and upstream wheel for `cryptography` with embedded OpenSSL).

Would also like to shorten GIT rev from 8 to 7 characters, to match GitHub's short revs. What do you think?

**needs-review**

**Comment by adiroiban** [comment]
> Fine with using the following `OS` names?

yes. is much better than what is now in the PR :)



> Would also like to shorten GIT rev from 8 to 7 characters, to match GitHub's short revs. What do you think?

there is the possibility of getting a conflict with a size of 7

if you run `got --pretty=format:'%h %an %ad %s' --date=short -10` on chevah/server you get 8 ...but on chevah/keycert is 7.

now I don't know if we publish to production for that conflict, so I would say that the probability is low...and if you are annoyed by 8 chars, we can use that.

I prefer to have them at 8 or longer if needed (let git decide what is the minimum)

For example for chevah-keycert
you can use
https://github.com/chevah/chevah-keycert/commit/fc2e35b21e8c67225b9c53eadc24a0fb85ba652d
or
https://github.com/chevah/chevah-keycert/commit/fc2e
as there are no conflicts.

but for chevah/server for

https://github.com/chevah/server/pull/1545/commits/e1b3059f9e31bec27b2b1e383fb18c978dfb3aef

you can't use an URL of 5 chars....

but I not sure that this is due to the conflicts... because on chevah/keycert I don't see a redirect when using the short SHA....

my guess is that GitHub has 2 types of repos... small repos are handled by some type or server and larger repos by another type

**Comment by adiroiban** [comment]
ah... I forgot needs-changes

**Comment by dumol** [comment]
> > Fine with using the following `OS` names?
> 
> yes. is much better than what is now in the PR :)
> 
> > Would also like to shorten GIT rev from 8 to 7 characters, to match GitHub's short revs. What do you think?
> 
> there is the possibility of getting a conflict with a size of 7
> 
> if you run `got --pretty=format:'%h %an %ad %s' --date=short -10` on chevah/server you get 8 ...but on chevah/keycert is 7.
> 
> now I don't know if we publish to production for that conflict, so I would say that the probability is low...and if you are annoyed by 8 chars, we can use that.
> 
> I prefer to have them at 8 or longer if needed (let git decide what is the minimum)
> 
> […]

No biggie, was just getting annoyed by not being able to quickly copy/paste git revs for Python packages from GitHub, which only show 7 characters by default.

**Comment by dumol** [comment]
Also removed here special treatment for SLES 11 with Security Module. Buildmaster updated accordingly. While at it, have shrunk the list of the `review` target considerably for `python-package`, as starting Eliseni, Foi, Mosna, and so many other rarely-used VMs is not fun.

Updated spreadsheet with required dependency and associated exported CSV file. Have you looked at them? What do you think of this arrangement? Flat ODS file for easy editing in LibreOffice and exported CSV for easy-to-check diffs. 

On a related note, there is no longer any known security issue with `python-package` on all supported platforms. :-]

**needs-review**

**Comment by adiroiban** [comment]
looks good. thanks

changes-approved

**Pull request merged**
