### PR TITLE
[#5103] Build libffi on SLES.

### PR DESCRIPTION
**Pull request by dumol**
Scope
=====

We have inadvertently built our Python packages against a `libffi6` package from the _monitoring_ OpenSUSE repo for SLES, used for installing Zabbix.

Changes
=======

Just don't use any local `libffi` on SLES, as even the `libffi-devel` packages from the SDKs DVDs or repos try to replace the `libffi4` package available to be installed in a default setup with `libffi43` packages that come with no vendor support.

We have a similar situation with AIX / HP-UX / the BSDs, where we use our own `libffi`.

To be extra safe, have removed `libffi-devel and libffi6` from SLES minions through Salt.

**Drive-by fixes**:
  * updated `paver.sh` with latest Ubuntu-related improvements from https://github.com/chevah/salt-master/pull/391
  * use stderr when erroring out from `chevah_build`
  * removed unused `libffi-3.3-rc0` sources.

How to try and test the changes
===============================

reviewers: @adiroiban 

Please review changes.

Run the automated tests.

### CODE REVIEW

**Comment by dumol** [comment]
**needs-review**

**Comment by adiroiban** [comment]
Thanks. I am now testing this as part of https://github.com/chevah/server/pull/1443

**Comment by dumol** [comment]
> Thanks. I am now testing this as part of [chevah/server#1443](https://github.com/chevah/server/pull/1443)

This revision won't work on server, as it uses PyCryptodome. To fix this in `server` I'll have to branch out from latest revision still using PyCrypto: https://github.com/chevah/python-package/commit/1afde4e1b147cbb27ac4d42ea5da108f8d010793

**Comment by dumol** [comment]
I already did something similar in https://github.com/chevah/python-package/pull/118 for specific Debian 7 packages.

**Pull request merged**
