### PR TITLE
[#3405] Update for OpenBSD 5.9.

### PR DESCRIPTION
**Pull request by dumol**
Scope
=====

Update `python-package` for OpenBSD 5.9.

Changes
=======

Pulled all changes from master, where the problem with newest OpenSSL versions was solved for Arch Linux and Ubuntu 16.04.
Updated the hardcoded OpenBSD version from 5.8 to 5.9.

**Drive-by fixes**:
  * update `paver.sh` from `salt-master` (a minor fix for OS X and an improved comment).

How to try and test the changes
===============================

reviewers: @adiroiban 

Please review the changes.
Run the automated tests through `paver_review`.

### CODE REVIEW

**Comment by dumol** [comment]
Branch: 3405-openbsd59-update
Build status: SUCCESS
Authors:
Duration: 1 hours, 24 minutes, 30 seconds
Full logs: https://buildbot.chevah.com:10443/builders/python-package-gk-review/builds/15

**needs-review**

**Comment by adiroiban** [comment]
all good. thanks

changes-approved

**Comment by adiroiban** [comment]
after this is merged, please also carpe-diem a commit in brink with the latest paver.sh changes :) thanks

**Comment by dumol** [comment]
Thanks, I already  have a ticket for `brink` too…

**Pull request closed without merging**
