### PR TITLE
[#3355] Update Python distribtuion on Windows for pyopnessl

### PR DESCRIPTION
**Pull request by adiroiban**
Scope
=====

We need pyopenssl 16.0.0 to re-enable FTPS tests on Windows.

Changes
=======

Update the versions... as pyopenssl requried an update pycrypto which required an update cffi :)

@alibotean there is an error in the build... it was also present 5 months ago. Can you please check it.

```
./chevahbs: line 179: /c/Users/buildslave/chevah/bs/python-package-win-xp-dev/build/build/python2.7-windows-x86/lib/Lib/site-packages/win32/pythoncomloader27.dll.embedded: No such file or directory
```

I also plan to update the python distro to 2.7.11

How to test
=========

reviewers: @alibotean 

check that the build from testing works for you.

After this is in production we might need to follow-up with a ticket on server to advertise the opnenssl update on windows

thanks!

### CODE REVIEW

**Comment by adiroiban** [comment]
I tried to build 2.7.11 but it failed.

@alibotean please check the 2.7.11 build, maybe you had an idea why it fails... otherwise we can merge this branch with 2.7.10 and only updated libs

needs-review

**Comment by alibotean** [comment]
> I tried to build 2.7.11 but it failed.

It works out of the box (sort of speak :smile:). Just updated our `buildbot`, `brink`, URLs for `pypi` and I got a succesfull build right off the bat.

https://buildbot.chevah.com:10443/builders/python-package-win-xp-dev/builds/89

**Comment by alibotean** [comment]
Now, the question is what do we do with the Linux/Unix version? The way it's now we use only one special case (solaris) all the others use the same Python version.

Would you or @dumol also update for Linux or should I make a special case for Windows as we have for Solaris?

**Comment by adiroiban** [comment]
> Would you or @dumol also update for Linux or should I make a special case for Windows as we have for Solaris?

we should also upgrade linux...but in a separate branch... feel free to not touch the linux/unix part

**Comment by alibotean** [comment]
Fixored: 

```
Extracting manifest to "c:/Users/buildslave/chevah/bs/python-package-win-xp-dev/build/build/python2.7-windows-x86/lib/Lib/site-packages/pywin32_system32/pythoncomloader27.dll.embedded"...
Removed SxS manifest from "c:/Users/buildslave/chevah/bs/python-package-win-xp-dev/build/build/python2.7-windows-x86/lib/Lib/site-packages/pywin32_system32/pythoncomloader27.dll".
```

**Comment by adiroiban** [comment]
Happy with this.

Pushed in production. I will follow up with a ticket to update this on server and include a release notes about the new OpenSSL version.

I will follow up with a ticket to also update python 2.7.11 on Linux and Windows.

Maybe @brunogola  can do this as part of the SSLv3 hack or otherwise we can ask @dumol  to update it.


needs-review

**Comment by alibotean** [comment]
changes-approved

**Pull request closed without merging**
