### PR TITLE
[#4401] libedit fixes.

### PR DESCRIPTION
**Pull request by dumol**
Scope
=====

Botched output after using `readline` module in Ubuntu.

With our Python package, `import readline`, which seems to works well, and then exit the interpreter. The console output is botched afterwards, you have to `reset` the console to get normal output back.

Changes
=======

Updated `libedit` sources from upstream.
Added patch to fix this issue from https://trac.macports.org/ticket/48807#comment:141.

**Drive-by changes**:
  * updated `paver.conf` to use latest Python packages
  * added `readline` support for Arch Linux, MacOS, FreeBSD and Solaris 11
  * document where `readline` support is not possible with current `libedit` version.

How to try and test the changes
===============================

reviewers: @adiroiban 

Please review the changes outside `src/libedit/libedit-*` (everything except the second commit).
Test the new binary in your OS for botched terminal settings after exiting the repl.
Run the automated tests.

### CODE REVIEW

**Comment by dumol** [comment]
Hhmm, interesting… Thanks for the feedback! So:
```
$ stty
speed 9600 baud; line = 0;
eol = M-^?; eol2 = M-^?;
-brkint ixany
-echok
$ ./build/python2.7-ubuntu1604-x64/bin/python 
Python 2.7.14 (9d506c63, Nov  8 2017, 13:08:38) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> ^D>>> 
$ speed 9600 baud; line = 0;
eof = <undef>; rprnt = <undef>; werase = <undef>; lnext = <undef>; min = 1; time = 0;
-brkint inlcr ixany
-icanon -iexten -echo -echok
$ Python 2.7.14 (9d506c63, Nov  8 2017, 13:08:38) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
>>> $ stty
speed 9600 baud; line = 0;
-brkint ixany
-echok
```
@adiroiban, you might want to use `stty sane` instead of `reset`, as it doesn't clean up the screen:
```
$ stty sane
$ stty
speed 9600 baud; line = 0;
```

**Comment by dumol** [comment]
Upstream bug: https://gnats.netbsd.org/48957

**Comment by dumol** [comment]
For reference, a better fix is available here: https://trac.macports.org/ticket/48807#comment:141

**Comment by adiroiban** [comment]
thanks for the info and `stty sane`

**Comment by dumol** [comment]
With updated sources, I have retested all supported platforms for `readline` support through `libedit` and tried to solve the remaining issues. Only AIX, HP-UX and  Solaris 10 are still without `readline` support. I think it's possible to get at least Solaris 10 on-board with an older version. If you think that we need that, I could dedicate some more time to it.

**needs-review**

**Comment by dumol** [comment]
Command-line for diff to review: 
```
git diff master chevah_build paver.conf python-modules/chevah-python-test/test_python_binary_dist.py src/libedit/chevahbs  src/libedit/terminal_restore.patch  src/python/chevahbs 
```
Review build: https://chevah.com/buildbot/builders/python-package-gk-review/builds/0

**Pull request merged**
